### ISSUE TITLE
Aplicativo não adiciona um storage pesquisado ao Setup

### ISSUE THREAD

**Issue by ronaldocoding** [Ronaldo64/setup-builder#5]
#### Aplicativo não adiciona um storage que foi pesquisado ao setup

Ao se pesquisar por um storage não é possível adicioná-lo ao setup e se a ação for repetida, o app fecha repentinamente por apresentar "falhas continuamente".

**Comment by monikode** [comment]
Eu testei aqui e funcionou

**Comment by ronaldocoding** [comment]
Bug consertado. O bug não ocorria necessariamente com um storage pesquisado, mas sim com vários. As causas ainda devem ser investigadas. Era um erro de casting de string para double. O erro foi resolvido substituindo o casting por uma conversão simples. Possíveis causas:

1) O erro ocorria com mais frequência em storages do mesmo departamento ou categoria

2) Geralmente os storages bugados estavam em uma certa faixa de preço (preço alto)
